services:
    _defaults:
        public: true

    # テスト時はCsrfTokenManagerはMockを利用する
    security.csrf.token_manager:
        class: Eccube\Tests\Mock\CsrfTokenManagerMock
        public: true
    # テスト時はTransactionListenerを無効にする
    Eccube\EventListener\TransactionListener:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - false
    # セッションの保存先をvar/sessions/testに変更する
    session.storage.mock_file:
        class: 'Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorage'
        arguments:
            - '%session.save_path%'
            - 'MOCKSESSID'
            - '@session.storage.metadata_bag'
    Eccube\Service\PurchaseFlow\Processor\DeliveryFeePreprocessor:
        autowire: true
        public: true
    Eccube\Service\PurchaseFlow\Processor\PaymentChargePreprocessor:
        autowire: true
        public: true
    Eccube\Service\PurchaseFlow\Processor\StockMultipleValidator:
        autowire: true
        public: true
    Eccube\Service\PurchaseFlow\Processor\SaleLimitMultipleValidator:
        autowire: true
        public: true
    Eccube\Service\PurchaseFlow\Processor\StockReduceProcessor:
        autowire: true
        public: true
    Eccube\Service\PurchaseFlow\Processor\StockValidator:
        autowire: true
        public: true
    Eccube\Service\PurchaseFlow\Processor\TaxProcessor:
        autowire: true
        public: true
