# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel.
version: 4.0.x-{build}

clone_folder: c:\projects\ec-cube

cache:
  - '%LOCALAPPDATA%\Composer\files'
  - vendor
  - bin\.phpunit
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

environment:
  global:
    DATABASE_URL: "mysql://root:Password12!@localhost/myapp_test"
    DATABASE_SERVER_VERSION: "5"
    BASE_DIR: "C:/projects/ec-cube"

  matrix:
  - db: mysql
    provider: mysql

services:
  - mysql

# Install scripts. (runs after repo cloning)
install:
  # see https://github.com/phpmd/phpmd/blob/master/appveyor.yml#L10-L13
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - sc config wuauserv start= auto
  - net start wuauserv
  # Set MySQL.
  - cp tests/my.cnf c:\
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.7\bin\;%PATH%
  #- cinst mysql
  #- SET PATH=C:\tools\mysql\current\bin\;%PATH%
  # Set PHP.
  - cinst php --version 7.2.8 --allow-empty-checksums
  - SET PATH=C:\tools\php72\;%PATH%
  - copy C:\tools\php72\php.ini-production C:\tools\php72\php.ini
  - echo date.timezone="Asia/Tokyo" >> C:\tools\php72\php.ini
  - echo extension_dir=ext >> C:\tools\php72\php.ini
  - echo extension=php_gd2.dll >> C:\tools\php72\php.ini
  - echo extension=php_mbstring.dll >> C:\tools\php72\php.ini
  - echo extension=php_pgsql.dll >> C:\tools\php72\php.ini
  - echo extension=php_pdo_mysql.dll >> C:\tools\php72\php.ini
  - echo extension=php_pdo_pgsql.dll >> C:\tools\php72\php.ini
  - echo extension=php_curl.dll >> C:\tools\php72\php.ini
  - echo extension=php_fileinfo.dll >> C:\tools\php72\php.ini
  - echo extension=php_intl.dll >> C:\tools\php72\php.ini
  - echo extension=php_openssl.dll >> C:\tools\php72\php.ini
  - echo memory_limit = 512M >> C:\tools\php72\php.ini
  - echo APP_ENV=codeception >> .env
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --dev --no-interaction -o

# Don't actually build.
build: off

before_test:
  - php bin\console doctrine:database:create
  - php bin\console doctrine:schema:create
  - php bin\console eccube:fixtures:load

test_script:
  - php bin\phpunit --exclude-group cache-clear
