# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel.
version: 3.0.x-{build}

clone_folder: c:\projects\ec-cube

cache:
  - '%LOCALAPPDATA%\Composer\files'
  
# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

environment:
  global:
    USER: "root" 
    DBNAME: "myapp_test"
    DBPASS: "Password12!"
    DBUSER: "root"
    BASE_DIR: "C:/projects/ec-cube"

  matrix:
  - db: mysql
    provider: mysql

services:
  - iis  
  - mysql

# Install scripts. (runs after repo cloning)
install:
  # Set MySQL.
  - cp tests/my.cnf c:\
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.7\bin\;%PATH%
  #- cinst mysql
  #- SET PATH=C:\tools\mysql\current\bin\;%PATH%
  # Set PHP.
  - cinst php --version 7.0.9
  - SET PATH=C:\tools\php\;%PATH%
  - copy C:\tools\php\php.ini-production C:\tools\php\php.ini
  - echo date.timezone="Asia/Tokyo" >> C:\tools\php\php.ini
  - echo extension_dir=ext >> C:\tools\php\php.ini
  - echo extension=php_openssl.dll >> C:\tools\php\php.ini
  - echo extension=php_gd2.dll >> C:\tools\php\php.ini
  - echo extension=php_mbstring.dll >> C:\tools\php\php.ini
  - echo extension=php_pgsql.dll >> C:\tools\php\php.ini
  - echo extension=php_pdo_mysql.dll >> C:\tools\php\php.ini
  - echo extension=php_pdo_pgsql.dll >> C:\tools\php\php.ini
  - echo extension=php_curl.dll >> C:\tools\php\php.ini
  - echo extension=php_fileinfo.dll >> C:\tools\php\php.ini
  - echo output_buffering = Off >> C:\tools\php\php.ini
  - echo default_charset = UTF-8 >> C:\tools\php\php.ini
  - echo mbstring.language = Japanese >> C:\tools\php\php.ini
  - echo mbstring.encoding_translation = On >> C:\tools\php\php.ini
  - echo mbstring.http_input = UTF-8 >> C:\tools\php\php.ini
  - echo mbstring.http_output = pass >> C:\tools\php\php.ini
  - echo mbstring.internal_encoding = UTF-8 >> C:\tools\php\php.ini
  - echo memory_limit = 512M >> C:\tools\php\php.ini
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --dev --no-interaction -o

# cache:
  # - C:\ProgramData\chocolatey\bin -> appveyor.yml
  # - C:\ProgramData\chocolatey\lib -> appveyor.yml

# Don't actually build.
build: off

before_test:
  - php eccube_install.php mysql none

test_script:
  - vendor\bin\phpunit.bat
